### ISSUE TITLE
Add verbose messages

### ISSUE THREAD

**Issue by FiksII** [sgubianpm/pygensa#2]
It will be nice to have simple convergence messages, like in scipy.optimize.

**Comment by sgubianpm** [comment]
@FiksII , thanks for this. This algorithm is now part or SciPy (called ``dual_annealing``) and is aligned with scipy optimize interface.
You can now use the callback mechanism which means each time the algorithm finds a better value, the callback function is called with the x components and the current objective value. This maybe what you need.

**Comment by sgubianpm** [comment]
@FiksII , you can refer to:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.dual_annealing.html#scipy.optimize.dual_annealing

**Comment by FiksII** [comment]
Yes, I have already found it. Thanks.
